pages:
  before_script:
  - apt-get update -y
  - apt-get install -y pandoc
  script:
  - cd docs
  - bash generate.sh
  artifacts:
    # prevent storage increase
    # in period of inactivity a weekly CRON regenerate the site
    expire_in: 1 week
    paths:
    - public
  only:
  - master
  - merge_requests

release:
  image: dlang2/ldc-ubuntu
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
  - apt-get update -y
  # deps, packaging tools
  - apt-get install -y rpm
  - apt-get install -y git
  - apt-get install -y zip
  - apt-get install -y libcurl4-openssl-dev
  - apt-get install -y git-lfs && git lfs install
  # gitlab Ubuntu-based runners default to LD gold
  # but linking lazarus programs requires LD bfd.
  - update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.bfd" 20
  - update-alternatives --install "/usr/bin/ld" "ld" "/usr/bin/ld.gold" 10
  - update-alternatives --config ld
  - ld --version
  # lazarus
  - git clone https://gitlab.com/basile.b/laz-bin-cache.git
  - cd laz-bin-cache
  - apt install -y ./fpc-laz_3.2.0-1_amd64.deb
  - apt install -y ./fpc-src_3.2.0-1_amd64.deb
  - apt install -y ./lazarus-project_2.0.10-0_amd64.deb
  - cd ..
  script:
  - bash setup/build-release.sh
  artifacts:
    paths:
    - setup/output/
  only:
  - tags
  - merge_requests
