pages:
  before_script:
  - apt-get update -y
  - apt-get install -y pandoc
  script:
  - cd docs
  - bash generate.sh
  artifacts:
    # prevent storage increase
    # in period of inactivity a weekly CRON regenerate the site
    expire_in: 1 week
    paths:
    - public
  only:
  - master
  - merge_requests

release:
  image: dlang2/ldc-ubuntu
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
  - apt-get update -y
  - apt-get install -y dpkg
  - apt-get install -y rpm
  - apt-get install -y git
  - apt-get install -y zip
  - curl -JLO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.6/fpc-laz_3.0.4-1_amd64.deb/download && apt install -y ./fpc-laz_3.0.4-1_amd64.deb
  - curl -JLO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.6/fpc-src_3.0.4-2_amd64.deb/download && apt install -y ./fpc-src_3.0.4-2_amd64.deb
  - curl -JLO https://sourceforge.net/projects/lazarus/files/Lazarus%20Linux%20amd64%20DEB/Lazarus%202.0.6/lazarus-project_2.0.6-0_amd64.deb/download && apt install -y ./lazarus-project_2.0.6-0_amd64.deb
  script:
  - bash setup/build-release.sh
  artifacts:
    paths:
    - setup/output/
  only:
  - tags
  - merge_requests
